const data={
quantumtrace:{title:'QuantumTrace',img:'photo2.png',problem:'Digital documents can be redistributed after legitimate decryption, making it difficult to identify the recipient or session associated with a leaked copy.',tech:['Python','Flask','Cryptography','SHA3-256','Digital Watermarking','Blockchain / DLT'],overview:'Forensic watermark system for secure document distribution.',features:['Session-specific watermark','Recipient binding','Audit record','Tamper-evident verification']},
agrivoice:{title:'AgriVoice',img:'photo3.png',problem:'Farmers need accessible guidance for crop selection, disease identification and agriculture-related decisions.',tech:['Python','NLP','Machine Learning','OpenCV','Flask'],overview:'AI-powered crop and farmer assistance system.',features:['Crop recommendation','Disease assistance','Voice interaction']},
mood:{title:'Mood Predictor',img:'photo4.png',problem:'Users may want a lightweight way to understand mood-related patterns from their inputs.',tech:['Python','Scikit-learn','Pandas','NumPy','Flask'],overview:'Machine-learning web application for mood prediction.',features:['Input preprocessing','ML prediction','Result visualization']},
md:{title:'MD Photography',img:'photo5.png',problem:'Photography clients need a clear way to explore packages, view work and submit booking information through one interface.',tech:['HTML','CSS','JavaScript','Flask','SQLite'],overview:'Freelancing photography booking system and portfolio.',features:['Portfolio','Packages','Booking workflow','Responsive UI']}
};
const key=new URLSearchParams(location.search).get('project')||'quantumtrace',p=data[key]||data.quantumtrace;
document.title=p.title+' | Project Details';
document.getElementById('detail').innerHTML=`<article class="detail-card panel"><div class="detail-top"><div class="detail-img image-box"><img src="../gallery/${p.img}" alt="${p.title}" onerror="this.style.display='none'"></div><div><span class="badge">Complete Project</span><h1>${p.title}</h1><p>${p.overview}</p><div class="detail-actions"><a class="btn dark" href="https://github.com/" target="_blank">GitHub</a><a class="btn" href="${key==='quantumtrace'?'https://quantumtrace-3t8k.onrender.com/':'https://example.com/'}" target="_blank">Live Demo</a></div></div></div><section class="detail-section panel"><h2>Problem Statement</h2><p>${p.problem}</p></section><section class="detail-section panel"><h2>Key Features</h2><div class="tags">${p.features.map(x=>`<span class="tag">${x}</span>`).join('')}</div></section><section class="detail-section panel"><h2>Technology Used</h2><div class="tags">${p.tech.map(x=>`<span class="tag">${x}</span>`).join('')}</div></section></article>`;
